### ISSUE TITLE
TypeError: Cannot destructure property `cmcPriceUsd` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by CHMEX** [atomiclabs/hyperdex#238]
After logging in to my portfolio I'm presented with the below message. The app does not continue.
This is on Windows 10 

Unhandled Promise Rejection
TypeError: Cannot destructure property `cmcPriceUsd` of 'undefined' or 'null'.
    at ActivityItem (app://-/bundle.js:82430:89)
    at beginWork (app://-/bundle.js:111900:36)
    at e (app://-/bundle.js:111939:105)
    at f (app://-/bundle.js:111939:379)
    at G (app://-/bundle.js:111945:329)
    at x (app://-/bundle.js:111944:378)
    at n (app://-/bundle.js:111944:221)
    at B (app://-/bundle.js:111943:117)
    at v (app://-/bundle.js:111942:51)
    at Object.enqueueSetState (app://-/bundle.js:111873:32)

![image](https://user-images.githubusercontent.com/33424502/40272208-53e7357c-5baa-11e8-992d-7def8a5f2c09.png)

---

HyperDEX Nightly 0.0.0-a36030c-18.5.19.1359
Electron 2.0.1
win32 10.0.16299
Locale: en-US

**Comment by sindresorhus** [comment]
I think we fixed this a while back. @CHMEX Do you still see this in the latest alpha version?
