### ISSUE TITLE
Error while trying to delete swap history

### ISSUE THREAD

**Issue by iujzvbc** [atomiclabs/hyperdex#458]
Important: If you have used any previous beta version, you need to delete your trade history as this version has an incompatible format. Right after opening this version, go to the "Debug" menu and choose "Delete Trade History".

That's what I did ("Delete *swap* history"), and I got this:

"Unhandled Error
NonError: null
    at module.exports.input (app://-/bundle.js:104255:10)
    at handleError (app://-/bundle.js:104357:9)
    at error (app://-/bundle.js:104394:4)
    at invokeFunc (app://-/bundle.js:104017:19)
    at trailingEdge (app://-/bundle.js:104064:14)
    at timerExpired (app://-/bundle.js:104052:14)"

**Comment by sindresorhus** [comment]
You have to be logged in to your portfolio when clicking "Delete swap history". Our fault for not clarifying that.
