### ISSUE TITLE
Error popup.

### ISSUE THREAD

**Issue by goldenman-kmd** [atomiclabs/hyperdex#503]
Unhandled Promise Rejection
TypeError: Cannot read property 'find' of undefined
    at messages.forEach.message (app://-/bundle.js:82781:43)
    at Array.forEach (<anonymous>)
    at _formatSwap (app://-/bundle.js:82738:14)
    at Array.map (<anonymous>)
    at SwapDB.getSwaps (app://-/bundle.js:82889:21)
    at <anonymous>

---

HyperDEX 0.1.0-alpha.13
Electron 2.0.8
win32 10.0.17134
Locale: ko

**Comment by sindresorhus** [comment]
Duplicate of #456
