### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by jdmarlow86** [atomiclabs/hyperdex#525]
Version: beta 0.1.0
OS: Windows
Errors: none
Severity: High (1)

**Comment by Hermes08** [comment]
Hi there 

Just to leave a reply on a similar error I saw. Windows.

Uncaught (in promise) Error: Could not call remote function 'showErrorBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 1, conversion failure from #<Object>
Error: Could not call remote function 'showErrorBox'. Check that the function signature is correct. Underlying error: Error processing argument at index 1, conversion failure from #<Object>
    at callFunction (C:\Users\Windows\AppData\Local\Programs\hyperdex\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Users\Windows\AppData\Local\Programs\hyperdex\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\Windows\AppData\Local\Programs\hyperdex\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at callFunction (C:\Users\Windows\AppData\Local\Programs\hyperdex\resources\electron.asar\browser\rpc-server.js:257:11)
    at EventEmitter.<anonymous> (C:\Users\Windows\AppData\Local\Programs\hyperdex\resources\electron.asar\browser\rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\Windows\AppData\Local\Programs\hyperdex\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (C:\Users\Windows\AppData\Local\Programs\hyperdex\resources\electron.asar\renderer\api\remote.js:221:30)
    at metaToValue (C:\Users\Windows\AppData\Local\Programs\hyperdex\resources\electron.asar\renderer\api\remote.js:225:28)
    at Object.remoteMemberFunction (C:\Users\Windows\AppData\Local\Programs\hyperdex\resources\electron.asar\renderer\api\remote.js:125:16)
    at LoginBox._definePrope

<img width="510" alt="hdexerror" src="https://user-images.githubusercontent.com/42009518/45714620-cff09700-bb57-11e8-8861-56fbaa7b14b9.png">

**Comment by lukechilds** [comment]
Thanks for reporting @jdmarlow86 and thanks for the info @Hermes08.

Seems possibly this could be related to #519

cc @sindresorhus

**Comment by lukechilds** [comment]
More context from Discord: https://discordapp.com/channels/412898016371015680/449948353531478037/491691040424722433

```
unquale at 20:24
I couldn't make it login in windows

Hermes at 20:28
Which version of Windows you are using? ,  Also guys remember that if you are going to delete the previous version make sure that you have your seed passphrase saved. I also saw a login error on Mac will try again.

lukechilds at 20:35
If you can create issues on GitHub with as much information as possible about the errors you're experiencing that would be very helpfull
If you get an error message can you copy/paste or screenshot into the issue
that helps us a tonne in tracking down the issue
@passcombo.com probably not for a while, we're waiting on mmv2 to be released first which looks like it should be much more stable

Jonathan at 20:49
I made one @lukechilds for Windows - there weren't any errors just couldn't log in

lukechilds at 20:49
When you say couldn't log in, was it just loading for a long time?
with the logging in loader spinning?
or did it literally not do anything when you clicked the login button?

Jonathan at 20:50
Nope it just resfreshes the screen/clears out the PW field

lukechilds at 21:01
when you click the login button?

Hermes at 21:02
The login issue was solved in Mac by doing a fresh installation
will write you on github also if I see something else

Jonathan at 21:55
Yes @lukechilds - to be sure I reverted back to the previous version and there was no issue
```

**Comment by lukechilds** [comment]
Thanks for your help guys, this should be resolved very soon: https://github.com/atomiclabs/hyperdex/pull/526

**Comment by sindresorhus** [comment]
A new release is out that fixes this: https://github.com/atomiclabs/hyperdex/releases/latest
