### ISSUE TITLE
Errors on MacOSx

### ISSUE THREAD

**Issue by dudezmobi** [atomiclabs/hyperdex#529]
```
Unhandled Promise Rejection
TypeError: Cannot read property 'find' of undefined
    at messages.forEach.message (app://-/bundle.js:82903:43)
    at Array.forEach (<anonymous>)
    at _formatSwap (app://-/bundle.js:82860:14)
    at Array.map (<anonymous>)
    at SwapDB.getSwaps (app://-/bundle.js:83011:21)
```

HyperDEX 0.1.3
Electron 3.0.0
darwin 17.6.0
Locale: en-US

**Comment by sindresorhus** [comment]
Did you previously try out any of the alpha versions? If so, you need to follow the steps here:

> Important: If you're upgrading from alpha.10, you need to delete your trade history as this version has an incompatible format. Right after opening this version, log in to your portfolio, go to the "Debug" menu and choose "Delete Trade History".
