### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XwhitewidowX** [atomiclabs/hyperdex#532]
Unhandled Promise Rejection
TypeError: Cannot read property 'find' of undefined
    at messages.forEach.message (app://-/bundle.js:82903:43)
    at Array.forEach (<anonymous>)
    at _formatSwap (app://-/bundle.js:82860:14)
    at Array.map (<anonymous>)
    at SwapDB.getSwaps (app://-/bundle.js:83011:21)

OS: Windows 10 64 bit

---

HyperDEX 0.1.3
Electron 3.0.0
win32 10.0.17134
Locale: nl

**Comment by sindresorhus** [comment]
Duplicate of #456
