### ISSUE TITLE
 Cannot read property 'uuid' of undefined

### ISSUE THREAD

**Issue by smk762** [atomiclabs/hyperdex#606]
```
TypeError: Cannot read property 'uuid' of undefined
    at app://-/bundle.js:105054:55
    at app://-/bundle.js:105118:7
```

attempt a 1:1 Rick:Morty swap from a restored wallet

---

HyperDEX 0.4.0
Electron 5.0.7
linux 4.15.0-54-generic
Locale: en-GB

**Comment by lukechilds** [comment]
@sindresorhus is this resolved in https://github.com/atomiclabs/hyperdex/commit/50ecc8a7cf0089563885855151b8bab0bdfe12bf?
