### ISSUE TITLE
Issue creating an order

### ISSUE THREAD

**Issue by 27aume** [atomiclabs/hyperdex#617]
When trying to create an order on DOGE_KMD
When I click on sell DOGE
I get error:
`TypeError: Request to marketmaker failed`

Then when i click on Log swaps (in the top menu):
I get
Unhandled Error
SyntaxError: missing ) after argument list
    at WebFrame.(anonymous function) [as executeJavaScript] (/tmp/.mount_hyperdqDyxmB/resources/electron.asar/renderer/api/web-frame.js:77:27)
    at /tmp/.mount_hyperdqDyxmB/resources/electron.asar/renderer/web-frame-init.js:15:33
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (/tmp/.mount_hyperdqDyxmB/resources/electron.asar/renderer/web-frame-init.js:14:5)

---

HyperDEX Nightly 0.0.0-c2d7531-19.7.24.1745
Electron 5.0.8
linux 5.0.0-23-generic
Locale: en-US

**Comment by 27aume** [comment]
Also Log container state doesnt do anything.
