### ISSUE TITLE
Error when clicking on exchange

### ISSUE THREAD

**Issue by lilszi** [atomiclabs/hyperdex#618]
Unhandled Promise Rejection
TypeError: Expected value to be a number
    at round (app://-/bundle.js:27227:9)
    at app://-/bundle.js:145601:31
    at Array.map (<anonymous>)
    at roundPrice (app://-/bundle.js:145600:35)
    at DepthChart (app://-/bundle.js:145642:10)
    at dh (app://-/bundle.js:95321:98)
    at Jh (app://-/bundle.js:95339:273)
    at mj (app://-/bundle.js:95420:277)
    at jj (app://-/bundle.js:95389:164)
    at Z (app://-/bundle.js:95383:471)

---
Windows 10

HyperDEX Nightly 0.0.0-ba617de-19.8.10.1752
Electron 5.0.9
win32 10.0.17763
Locale: en-GB

**Comment by lilszi** [comment]
On Ubuntu as well

**Comment by phideas** [comment]
```
TypeError: Expected value to be a number
    at round (app://-/bundle.js:27215:9)
    at app://-/bundle.js:145601:31
    at Array.map (<anonymous>)
    at roundPrice (app://-/bundle.js:145600:35)
    at DepthChart (app://-/bundle.js:145642:10)
    at dh (app://-/bundle.js:95309:98)
    at Jh (app://-/bundle.js:95327:273)
    at mj (app://-/bundle.js:95408:277)
    at jj (app://-/bundle.js:95377:164)
    at Z (app://-/bundle.js:95371:471)
```



Same issue confirmed on Ubuntu

---

HyperDEX Nightly 0.0.0-ba617de-19.8.12.1753
Electron 5.0.9
linux 4.15.0-55-generic
Locale: en-US

**Comment by lukechilds** [comment]
Thanks guys, will try to take a look into this later this week.

**Comment by lukechilds** [comment]
Can confirm the issue, working on a fix.

**Comment by lukechilds** [comment]
It seems a new version of market maker started returning order book prices as strings rather than numbers. This was causing an unhandled type error when trying to use number type functions on a string.

The issue is now resolved in master and should be in the next nightly build. Thanks for reporting!
